-- Procedure
CREATE OR REPLACE PROCEDURE SULAIMAN_PR_TEST(
    ERRBUF OUT VARCHAR2,
    RETCODE OUT NUMBER
)
IS
BEGIN
    FND_FILE.PUT_LINE(
        FND_FILE.OUTPUT,
        'WELCOME TO ORACLE EBS PROCEDURE!'
    );
END;
/
-- Function
CREATE OR REPLACE FUNCTION SULAIMAN_FN_TEST
RETURN VARCHAR2
IS
    SULAIMAN_MSG VARCHAR2(2000);
BEGIN
    SULAIMAN_MSG := 'WELCOME TO ORACLE EBS FUNCTION!';

    RETURN SULAIMAN_MSG;
END;
/