-- System Date Procedure
CREATE OR REPLACE PROCEDURE SULAIMAN_PR_SYSDT (ERRBUF OUT VARCHAR2, RETCODE OUT NUMBER)
IS
    V_DT DATE;
BEGIN
    SELECT SYSDATE INTO V_DT FROM DUAL;
    FND_FILE.PUT_LINE(FND_FILE.LOG, 'You Can See LOG DATAFILS Here!');
    FND_FILE.PUT_LINE(FND_FILE.OUTPUT, 'Current Date = ' || V_DT);
EXCEPTION
    WHEN OTHERS THEN
        FND_FILE.PUT_LINE(FND_FILE.OUTPUT, 'Check Your Program: ' || ERRBUF || ' ERRCODE = ' || RETCODE);
END;
/